language: node_js
node_js:
  - 0.12
env:
  global:
    - secure: pSwgbHl9hwmuq0jw9GZOO0ATbWg/6YgXLVtLS4cIwD7tTgHaLt5VSgapX+fVxqNaCiOb5ek5Np2BPWx8PpkvUr2VdAK6soTRocV0FGYmHLF683MBBswv5XUjxdnrmhEUcJpzfnwqgSEJ1UXOZPzmQehylvxwTCqMgsNoD27GBf+zbw+XozGJZ2NhBm/IaLB/eWfjIUdl1yzckWup/6U0C4loOYkLRn64r8LWL5Jihbsnzg0908zeVIb51sCqslR3FOpENSRKx7aCJhHcUlkARhak5Dkvf2t+u1GI2QTeMDqTeKgfOpMaEW/0VG1uh/ZMYCmIqhYrzP9Gxmh67bvrkF07+lVHl2JHbm4XP6y+PcuqMdeByYKyzBHCy1Ev5pP/3ZEpgJDEJ19HT3qiFvr6yMn3Fa/YdjGlMkVlFKf9w1ZsyE8SOlJZpYmSaij844FdnaXF3EDW2d2GG/mvCaGL4/dRAmBiDBzx8LWiX54/C3iJ8yKbFs0aHTPyJ+x9R3gMYdfJ1XadPsV8hgRlDuRoWjAZT4NoM/W9PKFXWGO+u5KZjQtpc9BC1V1TcKBPTRlx2T0HjgVF8K15j7Xj7pna3EMbikBA+3hzP4dFg+cRYs2EwsmflyWUVoZOd91za6RqJm+hBgh6sXJTvwZk6Xocs3HOFsLhLrP9wkpy4t2kLEA=
    - secure: y9Vp3wthfAst2koONZzUaMlNrPGICiXXtfbeYVv+sIQ3kZLu/2XrnS4tbqDkAdztpUVHOi/UBV0HuK+L4UlxB2CfJW5/QTcEltKhQIT1cSggbWkZgtW6nPmO3s8KAO4vV0XobmfcfhiX9VjXuZ24fXdB+rZuRDAy7Pc7tK1YiKTL8PpDI/EgWsvDH9OzZWipK908OnccEZfPa2wg79TsxPBdjq6/ZszA69HB8oL7cLh+uR55tB9NyfPDNJN4/X+dK8UjHob9hMBr0JnSxffQoJfEdUmoZm0mE9GDM3H2A/KJTcKhZwgZaysYdtT2HCe8cR9BLttQGQWBeefNnVa0goIbQKODDf/UIG6peqCh554qF7q8GTwXbXHydqPZbm6Ka6r0ltX7ZiFwz6HEo7Snu4to8nYfCYCaNUOHOtrLls9bjIpZUd9OqyDjA2fVKA4BYpQWu+nx3F1n8Qf9b5UKGzn8Ds4Xkk0E79BjfGqIcHUNQUjpzIbBhSgP9SIejGTK9m/mBCU3+ZCVs++f28Y8lnqubi4ijxIomFLsQmhNB8sMWQmxVHL2tn99+lxVdAbPmAT2oWO8KP9YD+StauU8qW/eVj50krfxyBUKtHPneaEoP4YTTgbKnGLA1CC325ZdWTzcvBw04t0ZadkvHEHOf6ZcZdYsyvBVVV/+URMC8zU=
addons:
  sauce_connect: true
branches:
  only:
    - master
    - /^greenkeeper/.*$/
